service: snapbuy-backend

frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DATABASE_HOST: ${env:DB_HOST}
    DATABASE_USER: ${env:DB_USERNAME}
    DATABASE_PASSWORD: ${env:DB_PASSWORD}
    DATABASE_NAME: ${env:DB_DATABASE}
    WOMPI_PRIVATE_KEY: ${env:WOMPI_PRIVATE_KEY}
    WOMPI_PUBLIC_KEY: ${env:WOMPI_PUBLIC_KEY}
    WOMPI_INTEGRITY_KEY: ${env:WOMPI_INTEGRITY_KEY}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    define: { 'require.resolve': undefined }
